export const FETCH_SEARCH_POST = 'FETCH_SEARCH_POST'
export const REQUESTED_SEARCH_POST = 'REQUESTED_SEARCH_POST'
export const RECEIVED_SEARCH_POST = 'RECEIVED_SEARCH_POST'
export const SEARCH_FAILED_POST = 'SEARCH_FAILED_POST'

export const FETCH_EDITED_POST = 'FETCH_EDITED_POST'
export const REQUESTED_EDITED_POST = 'REQUESTED_EDITED_POST'
export const RECEIVED_EDITED_POST = 'RECEIVED_EDITED_POST'
export const EDITED_FAILED_POST = 'EDITED_FAILED_POST'

export const FETCH_DELETED_POST = 'FETCH_DELETED_POST'
export const REQUESTED_DELETED_POST = 'REQUESTED_DELETED_POST'
export const RECEIVED_DELETED_POST = 'RECEIVED_DELETED_POST'
export const DELETED_FAILED_POST = 'DELETED_FAILED_POST'

export const FETCH_ADD_POST = 'FETCH_ADD_POST'
export const REQUESTED_ADDED_POST = 'REQUESTED_ADDED_POST'
export const RECEIVED_ADDED_POST = 'RECEIVED_ADDED_POST'
export const ADDED_FAILED_POST = 'ADDED_FAILED_POST'

export const FETCH_SEARCH_ALL_POSTS = 'FETCH_SEARCH_ALL_POSTS'
export const REQUESTED_SEARCH_ALL_POSTS = 'REQUESTED_SEARCH_ALL_POSTS'
export const RECEIVED_SEARCH_ALL_POSTS = 'RECEIVED_SEARCH_ALL_POSTS'
export const SEARCH_FAILED_ALL_POSTS = 'SEARCH_FAILED_ALL_POSTS'

export const FETCH_UPDATE_TITLE = 'FETCH_UPDATE_TITLE'
export const UPDATE_TITLE = 'UPDATE_TITLE'

export const FETCH_UPDATE_CONTENT = 'FETCH_UPDATE_CONTENT'
export const UPDATE_CONTENT = 'UPDATE_CONTENT'

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'
